// import Head from "next/head";
// import styles from "@/styles/Home.module.css";
// import SearchBar from "@/components/SearchBar";
// import { TextareaAutosize } from "@mui/base/TextareaAutosize";
// import { Button } from "@mui/material";

// import { Stack } from "@mui/material";
// import SearchIcon from "@mui/icons-material/Search";

// import Input from "@/components/atoms/Input";
// import { useEffect, useState } from "react";
// import { ApiServices } from "@/components/groqapi";

// export default function Home() {
//   const [searchBarInput, setSearchBarInput] = useState("");
//   const [newSearchBarInput, setNewSearchBarInput] = useState("");
//   const [groqResponse, setGroqResponse] = useState("");

//   const handleSearch = () => {
//     const inputValue = newSearchBarInput;
//     ApiServices.handleGroqApi({ inputValue })
//       .then((response) => {
//         response && setGroqResponse(response);
//         console.log("response in handleSearch");
//         console.log(response);
//       })
//       .catch((error) => {
//         console.error(error);
//       });
//     setSearchBarInput(inputValue);
//   };
//   // groqResponse !== "" && console.log(groqResponse);

//   const handleKeyDown = (event) => {
//     console.log("enter pressed");
//     if (event.key === "Enter") {
//       console.log("enter pressed in if");
//       handleSearch();
//     }
//   };
//   const handleKeyPress = (event) => {
//     console.log("enter pressed");
//     if (event.key === "Enter") {
//       handleSearch();
//     }
//   };
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={`${styles.center} "flex w-full"`}>
//           <Stack sx={{ width: "100%", height: "3.65rem" }}>
//             <Input
//               endIcon={<SearchIcon onClick={handleSearch} style={{ cursor: "pointer" }} />}
//               placeholder="type the query here .."
//               sx={{ minWidth: { md: "600px", xs: "auto" }, backgroundColor: "#ffffff", borderRadius: "4px" }}
//               value={newSearchBarInput}
//               onChange={(event) => setNewSearchBarInput(event.target.value)}
//               onKeyPress={handleKeyPress}
//               onKeyDown={handleKeyDown}
//               id="searchInput"
//             />
//           </Stack>
//         </div>
//         <TextareaAutosize
//           readOnly
//           minRows={10}
//           style={{ width: "70%", backgroundColor: "#fff" }}
//           value={groqResponse}
//         />
//       </main>
//     </>
//   );
// }

//========================================================================================================

// import Head from "next/head";
// import styles from "@/styles/Home.module.css";
// import { TextareaAutosize } from "@mui/base/TextareaAutosize";
// import { Stack } from "@mui/material";
// import SearchIcon from "@mui/icons-material/Search";
// import Input from "@/components/atoms/Input";
// import { useState } from "react";
// import { ApiServices } from "@/components/groqapi";

// export default function Home() {
//   const [newSearchBarInput, setNewSearchBarInput] = useState("");
//   const [groqResponse, setGroqResponse] = useState("");

//   const handleSearch = () => {
//     const inputValue = newSearchBarInput;
//     ApiServices.handleGroqApi({ inputValue })
//       .then((response) => {
//         if (response) {
//           setGroqResponse(response);
//           console.log("Response in handleSearch:", response);
//         }
//       })
//       .catch((error) => {
//         console.error("Error in handleSearch:", error);
//       });
//   };

//   const handleKeyDown = (event) => {
//     if (event.key === "Enter") {
//       handleSearch();
//     }
//   };

//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={`${styles.center} "flex w-full"`}>
//           <Stack sx={{ width: "100%", height: "3.65rem" }}>
//             <Input
//               endIcon={<SearchIcon onClick={handleSearch} style={{ cursor: "pointer" }} />}
//               placeholder="Type the query here..."
//               sx={{ minWidth: { md: "600px", xs: "auto" }, backgroundColor: "#ffffff", borderRadius: "4px" }}
//               value={newSearchBarInput}
//               onChange={(event) => setNewSearchBarInput(event.target.value)}
//               onKeyDown={handleKeyDown}
//               id="searchInput"
//             />
//           </Stack>
//         </div>
//         <TextareaAutosize
//           minRows={10}
//           style={{ width: "90%"}}
//           value={groqResponse && groqResponse}
//         />
//       </main>
//     </>
//   );
// }

//========================================================================================================


// import Head from "next/head";
// import styles from "@/styles/Home.module.css";
// import { TextareaAutosize } from "@mui/base/TextareaAutosize";
// import { Stack, Box, Typography, IconButton } from "@mui/material";
// import SearchIcon from "@mui/icons-material/Search";
// import Input from "@/components/atoms/Input";
// import { useState } from "react";
// import { ApiServices } from "@/components/groqapi";

// export default function Home() {
//   const [newSearchBarInput, setNewSearchBarInput] = useState("");
//   const [chatHistory, setChatHistory] = useState([]);

//   const handleSearch = () => {
//     const inputValue = newSearchBarInput;
//     setNewSearchBarInput("");
//     setChatHistory((prevHistory) => [
//       ...prevHistory,
//       { input: inputValue, response: "Loading..." }
//     ]);

//     ApiServices.handleGroqApi({ inputValue })
//       .then((response) => {
//         console.log("response: "+response);
//         setChatHistory((prevHistory) =>
//           prevHistory.map((entry, index) =>
//             index === prevHistory.length - 1
//               ? { ...entry, response }
//               : entry
//           )
//         );
//       })
//       .catch((error) => {
//         console.error("Error in handleSearch:", error);
//         setChatHistory((prevHistory) =>
//           prevHistory.map((entry, index) =>
//             index === prevHistory.length - 1
//               ? { ...entry, response: "Error occurred." }
//               : entry
//           )
//         );
//       });
//   };

//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={`${styles.center} "flex w-full"`}>
//           <Stack sx={{ width: "100%", height: "3.65rem" }}>
//             <Input
//               endIcon={
//                 <IconButton onClick={handleSearch}>
//                   <SearchIcon style={{ cursor: "pointer" }} />
//                 </IconButton>
//               }
//               placeholder="Type the query here..."
//               sx={{
//                 minWidth: { md: "600px", xs: "auto" },
//                 backgroundColor: "#ffffff",
//                 borderRadius: "4px",
//               }}
//               value={newSearchBarInput}
//               onChange={(event) => setNewSearchBarInput(event.target.value)}
//               id="searchInput"
//             />
//           </Stack>
//         </div>
//         <Box sx={{ width: "90%", mt: 2 }}>
//           {chatHistory.map((entry, index) => (
//             <Box key={index} sx={{ mb: 2 }}>
//               <Typography variant="body1" sx={{ fontWeight: "bold" }}>
//                 SearchText: {entry.input}
//               </Typography>
//               <TextareaAutosize
//                 minRows={3}
//                 style={{ minWidth: "90%", marginTop: "8px" }}
//                 value={entry.response}
//                 readOnly
//               />
//             </Box>
//           ))}
//         </Box>
//       </main>
//     </>
//   );
// }
//=================================================================

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { TextareaAutosize } from "@mui/base/TextareaAutosize";
import { Stack, Box, Typography, IconButton } from "@mui/material";
import SearchIcon from "@mui/icons-material/Search";
import Input from "@/components/atoms/Input";
import { useState } from "react";
import { ApiServices } from "@/components/groqapi";

export default function Home() {
  const [newSearchBarInput, setNewSearchBarInput] = useState("");
  const [chatHistory, setChatHistory] = useState([]);

  const handleSearch = () => {
    const inputValue = newSearchBarInput;
    setNewSearchBarInput("");
    setChatHistory((prevHistory) => [
      { input: inputValue, response: "Loading..." },
      ...prevHistory
    ]);

    ApiServices.handleGroqApi({ inputValue })
      .then((response) => {
        console.log("response: " + response);
        setChatHistory((prevHistory) =>
          prevHistory.map((entry, index) =>
            index === 0 ? { ...entry, response } : entry
          )
        );
      })
      .catch((error) => {
        console.error("Error in handleSearch:", error);
        setChatHistory((prevHistory) =>
          prevHistory.map((entry, index) =>
            index === 0 ? { ...entry, response: "Index Error occurred." } : entry
          )
        );
      });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Stack sx={{ width: "100%", height: "1rem" }}>
            <Input
              endIcon={
                <IconButton onClick={handleSearch}>
                  <SearchIcon style={{ cursor: "pointer" }} />
                </IconButton>
              }
              placeholder="Type the query here..."
              sx={{
                minWidth: { md: "600px", xs: "auto" },
                backgroundColor: "#ffffff",
                borderRadius: "4px",
              }}
              value={newSearchBarInput}
              onChange={(event) => setNewSearchBarInput(event.target.value)}
              id="searchInput"
            />
          </Stack>
        </div>
        <Box sx={{ width: "90%", mt: 2 }}>
          {chatHistory.map((entry, index) => (
            <Box key={index} sx={{ mb: 2 }}>
              <Typography variant="body1" sx={{ fontWeight: "bold" }}>
                SearchText: {entry.input}
              </Typography>
              <TextareaAutosize
                minRows={3}
                style={{ minWidth: "90%", marginTop: "8px" }}
                value={entry.response}
                readOnly
              />
            </Box>
          ))}
        </Box>
      </main>
    </>
  );
}
